### ISSUE TITLE
Link to OK Grow article for MongoDB Atlas oplog tailing no longer works

### ISSUE THREAD

**Issue by Rijk** [meteor/guide#1018]
I was trying to find out how to get Oplog tailing to work on Atlas, got to https://galaxy-guide.meteor.com/mongodb.html. This references an OK GROW article:

![image](https://user-images.githubusercontent.com/159500/71309004-45a27d00-2403-11ea-95d3-8971101a4edd.png)

But unfortunately, this article is no longer online: https://www.pauldowman.com/posts/shutting-down-okgrow. The Google cache doesn’t work either, nor does searching directly on Medium. It would be nice if the Guide just offers this information directly.

**Comment by StorytellerCZ** [comment]
Does anyone has the content?

**Comment by vparpoil** [comment]
Archive.org has it : 
https://web.archive.org/web/20191002223453/okgrow.com/posts/meteor-galaxy-ci-deployment
Here is an extracted PDF version I printed from the archive (because it needed to stop the loading process to avoid a redirect on the archived page)
[okgrow-oplog tailing.pdf](https://github.com/meteor/guide/files/4450467/okgrow-oplog.tailing.pdf)
