### ISSUE TITLE
Recommend bulk updates in migrations, rather than iterating over all items and running a new update query

### ISSUE THREAD

**Issue by stubailo** [meteor/guide#118]
http://guide.meteor.com/collections.html#Writing_migrations

**Comment by stubailo** [comment]
CC @debergalis

**Comment by stubailo** [comment]
Also, we should say which Mongo version you should be running

**Comment by tmeasday** [comment]
https://github.com/meteor/guide/commit/254693d8e5cca67fd65b87b23ded25823639000c

**Comment by tmeasday** [comment]
Please review I guess (probably should have sent a PR)

**Comment by tmeasday** [comment]
http://guide.meteor.com/collections.html#bulk-data-changes

**Comment by debergalis** [comment]
Might consider rephrasing this piece.  (There's also a typo in "it's a
cruder".)

"The downside is that it’s a cruder in that it operates on all documents at
once, which usually means you need to take your site down until the update
is happening (as the potential for “race” conditions is high)."

Instead I'd make the point that certain things aren't possible with bulk
updates in Mongo.  If you're $set-ing a field to a constant on every
document it's hard to imagine there's a downside to a bulk update.  But if
you need to $set the field to a value that depends on some other document
value, then you have no choice -- you need to do the read, run the
computation on the Meteor server, then do the write.

Assuming you're writing migrations in a two-phase way (as recommended later
in the article), I don't think there's much downside at all to writing them
as bulk updates.  We might want to make the point that some bulk updates
may lock the database for a long time and so occasionally it may be
necessary to run the bulk update in chunks.

Further down in the article, where you say migrations can take hours, I'd
clarify that to mean when you write them using the read-modify-set pattern,
rather than bulk pattern.  I'd be surprised if bulk updates take that long
on any but the largest production databases; those users will likely know
the situation.

Hmm.  Is there another pattern we can describe, where you use the Mongo
async API so that you can do a pipelined read-update on each document?  If
that's easy to support, it would almost always be preferable to serializing
the migration one document at a time per round trip to the DB.

Also, should we clarify that you need Mongo 2.6 *or above*?

**Comment by tmeasday** [comment]
> If you're $set-ing a field to a constant on every
document it's hard to imagine there's a downside to a bulk update.

I mean if you are doing this you can do `update({..}, {field: 'constant'}, {multi: true})` and be done with it. I should probably say that too though.

>  But if you need to $set the field to a value that depends on some other document value

Well you *can* do this with bulk updates (as you can see in the example). The problem is of course that if try and set (say) 10k todo counts at once, you are guaranteed to be wrong on some of them by the time the update goes through if the database is changing. This is why I suggest bulk updates are only really useful if you are willing to take down your server while you do them.

Of course you can be wrong if you do them one at a time too but it's at least unlikely in this case. Probably not good enough for big enough datasets though. I'm not quite sure how folks usually handle this.

Also, maybe there are some in-between use cases where bulk updates are good without stopping the app servers.

> We might want to make the point that some bulk updates
may lock the database for a long time and so occasionally it may be
necessary to run the bulk update in chunks

Yes

> Further down in the article, where you say migrations can take hours, I'd
clarify that to mean when you write them using the read-modify-set pattern,
rather than bulk pattern. 

Agreed.

> Is there another pattern we can describe, where you use the Mongo
async API so that you can do a pipelined read-update on each document? 

There may be something fancy you can do with aggregations but it would be very much a case-by-case style situation I imagine.

I actually have found that the document-at-time approach is OK in the two-phase situation where you don't care how long the migration takes (because the app works fine with old and new data). If you parallelize the code it usually doesn't take that long. I guess that won't work once you reach "web-scale" with your datasets though.

I suspect the `percolate:migrations` package could help you out a lot more with some of this too, btw.

**Comment by tmeasday** [comment]
Made some changes to address your points @debergalis https://github.com/meteor/guide/commit/a5d6a3a8e793167e255eb3b25b8444b839c6962a

**Comment by tmeasday** [comment]
Perhaps I should update the example to use an aggregation too?
