### ISSUE TITLE
Different places documentation lives now

### ISSUE THREAD

**Issue by robfallows** [meteor/guide#12]
As far as official (MDG) documentation is concerned we currently have [the docs](http://docs.meteor.com/#/full/), [the wiki](https://github.com/meteor/meteor/wiki), a number of READMEs in packages, [some of which](https://github.com/meteor/meteor/blob/devel/packages/tracker/README.md) are better than [others](https://github.com/meteor/meteor/blob/devel/packages/tinytest/README.md) and the [Meteor Manual](http://manual.meteor.com/) - does Maria still work at Meteor?

There is already an issue with overlaps (saying the same thing), contradictions (saying something different) and holes (not saying something).

A proportion of this project's time needs to be devoted to addressing the confusion surrounding all these disparate ways of presenting The Meteor Way.

@stubailo : I think you've already said the useful knowledge in the wiki will be absorbed into the guide?

I see the docs as the reference book - all methods, etc. are documented much as they are now, with links to the appropriate guide sections (and *vice versa*) - is that right?

I think the Meteor Manual should go the way of the dinosaur (think of it as a K/T meteoric extinction event :wink:) - maybe it could be a permanent redirect to the guide.

The package READMEs should all be high quality and become the appropriate package reference section in the guide (imported as part of the guide's build process).

What do you think?

**Comment by robfallows** [comment]
Okay - I've just read the [Guide Plan](https://github.com/meteor/guide/blob/gh-pages/research.md) and see that you've already stated that your intention is a single resource, which is cool. However, I sort of detected an intention to do away with READMEs - is that true?

**Comment by stubailo** [comment]
#### Meteor manual

We should take it down. It's already outdated, probably. That was a project we started but it didn't really pan out.

#### The wiki

I think GitHub wiki is basically the worst place for information ever. Biggest issues:

1. No redirects
2. No possibility for PRs
3. No organization/table of contents/anything else
4. Super limited formatting

I think we should move everything off of the Wiki and into some "errata" section of the guide as soon as possible.

#### READMEs in packages

I think these have a lot of problems on their own. I'm thinking we should get rid of them, since they have a variety of issues:

1. They are different depending on which branch of GitHub you're looking at, a problem made much worse since the default branch on GitHub is `devel`, which often has stuff that hasn't been released yet
2. They don't have organization, table of contents, etc
3. They are duplicated in several places - atmosphere, GitHub, etc - so there isn't a canonical place to link to documentation
4. You really have to be looking for that specific README to find the content you are looking for. Who know which package will have the docs you're looking for?

I think each README should just have the name of the package, a two sentence summary of what it's for, and link to the appropriate section of the docs and/or guide. We should also reduce the number of packages we have by getting rid of crap like `code-prettify` and `jquery-waypoints` etc.

#### Meteor docs

This site has its own plethora of issues. Right now it's the best we've got, but I hope that we can find a better home for all of this content. Here are the issues I see:

1. Atrocious SEO - somehow when you click on a Google link to the docs, you don't even end up on the right part of the page
2. Super slow to load - since all of the content is presented as one page, it incurs a huge loading and rendering burden on the browser. It basically doesn't work at all on mobile.
3. No clear separation of content - the content on docs.meteor.com is some combination of guides, trivia, and API reference
4. Hard to edit - it's a super custom website with no long-term strategy for content organization. The format worked when Meteor was still small, but now there are over 200 items in the table of contents which is pretty insane

Here's what I think we should do:

1. Finish the guide, and move all of the trivia/usage bits/examples out of the docs page into the guide
2. Create a totally new site just for API docs - with nice search, SEO, etc
3. Get rid of the current docs site

Then we'll end up with one site (the guide) with code samples, explanations, philosophy, getting started information, etc; and another site (the API docs) with organized references for API arguments, return values, etc.

What do you think of this strategy? There is definitely some conversation to be had about package READMEs, but I haven't found a great way of keeping them up to date. Maybe we could have a fancy build system and merge them with the guide, but the format of a great README is different from the format of a great guide article. I would rather not try to maintain both.

**Comment by tmeasday** [comment]
## READMES:

> default branch on GitHub is devel

Has this been thought through? This seems a mistake. Is it for PRs sake?

> Atmosphere

It's useful having a succinct summary on atmosphere isn't it? How would we achieve that w/o a README?

## Docs

:+1: I think this strategy has been expressed elsewhere and I am in complete agreement.

**Comment by tmeasday** [comment]
Also we need to figure out what to do with https://github.com/meteor/guide/issues/13

**Comment by stubailo** [comment]
The devel thing is almost certainly for PRs. I don't think there is a way to have a separate branch for PRs and for general viewing, unfortunately, and we don't accept PRs against master.

As for summaries on Atmosphere, that would be useful but now we have to remember to maintain the information in two places. I'd vote to have the summary on atmosphere be like one paragraph and a link to the docs/guide.

**Comment by tmeasday** [comment]
:+1:

**Comment by rhyslbw** [comment]
This is a good plan
