### ISSUE TITLE
Clarify how to override packages locally on Windows

### ISSUE THREAD

**Issue by stevehickman** [meteor/guide#193]
The section of the guide titled: 
**Overriding packages from Atmosphere with a local version**

contains the following text:

*A Meteor app can load packages in one of three ways, and it looks for a matching package name in the following order:

Package source code in the packages/ directory inside your app.*

The naming convention in Meteor is that packages are prefixed by the name of the package creator and that this prefix is separated from the package name by a colon ":". Colons are not valid characters in Windows. Meteor replaces these with "_" when installing packages (at least it does on Windows which is the OS I'm using). However, simply adding a subdirectory in the application 'packages' directory with the same name as generated by Meteor does not work, because "_" is not considered a valid character (Why does this inconsistency exist between how Meteor treats directory names for installed packages and overriding packages?). Instead, it generates this message:

**
=> Errors prevented startup:

   While reading package from `/D/GITRepos/FACEVPD/dataentry/packages/pascoual_bootstrap-contextmenu`:
   error: Package names can only contain lowercase ASCII alphanumerics, dash, dot, or colon, not "_".

**

In order to get this to work, I ended up renaming the directory **and** editing my packages file to remove the creator (pascoual) prefix from the package name.  The documentation should be updated to reflect this.

**Comment by stevehickman** [comment]
apparently Markdown treats underscores as some kind of special character. The original post above attempted to indicate that Meteor replaces colons with underscores when generating package subdirectory names. The sudden change into and out of italics above indicates where the underscores were in the original text.

**Comment by stubailo** [comment]
@stevehickman I think there is an alternate solution, which is hard to discover because it's not always clear how packages work in Meteor:

You should put the override package in a directory with a different name, and as long as the `package.js` file specifies the correct name with the colon, you're all good. You don't need to have any file paths with the actual name of the package on the FS.

We should add this as a note to the section, basically specific info about overriding packages on Windows.
