### ISSUE TITLE
Figure out how something becomes 'accepted' for publication

### ISSUE THREAD

**Issue by queso** [meteor/guide#2]
I assume we will all send in PR's to this repo. It would be nice to figure out how/when/why a PR should be accepted into the guide. This seems like the first major hurdle to developing trust with potential writers.

**Comment by tmeasday** [comment]
Agreed. I'm wondering in this space how/if we separate "wisdom from MDG" from "wisdom from the community"?

Not to say MDG has more wisdom (if anything probably not), but I do know that a lot of people would want to know what MDG's proscription on various topics is. If the thing feels too much like a community guide they might not feel they are getting that. 

Maybe that's fine though?

**Comment by tmeasday** [comment]
I guess what I am thinking is we could have various levels of community involvement:

1. Written exclusively by MDG, with minor corrections from the community (I doubt we want this).
2. Written by whoever, with MDG as exclusive curators via PR
3. As above with a trusted set of curators
4. Some kind of free-for-all with voting or something (This sounds like too much work to get right, better served by pure community efforts I'd say).

I don't know if there's much external difference between 2-3 but I think it's worth pondering.

**Comment by queso** [comment]
I think the difference between 2 and 3 is all about where the workload might lie. Not sure if that is externally visible, but having PRs sit for months doesn't sound awesome either.

**Comment by jesseflorig** [comment]
Since this is supposed to be THE meteor guide, shouldn't all of the content just have a "100% MDG Approved" badge and just give credit to relevant contributors?

**Comment by stubailo** [comment]
I think there are definitely two types of contributions:

1. Improvements and corrections to existing content
2. Submission of a new planned topic
3. Submission of a totally new, unplanned topic

I'd say that accepting improvements and corrections should be pretty straightforward, if they contribute to the clarity and coverage of the article.

Accepting totally new content will be more common at first, so we'll need to put in extra effort to evaluate and moderate it to make sure that:

1. It's appropriate content for the guide
2. It's the best practice that we want to espouse
3. The format is correct

I'd say that the most reasonable thing right now would be to check in before writing any totally new content to make sure that it's likely to be accepted _before_ writing anything. You can post an issue with a plan for what would be included, and then we can discuss if it makes sense in that form. That way we can all save time by not writing extra stuff we might not use.

**Comment by queso** [comment]
That seems practical to me for getting started. I am more worried about acceptance on the backend. MDG doesn't have a great track record of merging PRs, so I would love to see some efforts given to the community here to help with this effort.

**Comment by stubailo** [comment]
Yeah, I understand your frustration. It sounds like you're worried about the situation where we spend a couple months being excited about the guide, and then once we finished some initial work we don't really accept PRs and the thing stagnates a bit.

It's happened before! I think really the only thing that will help is a change in our company culture to give a lot more attention to PRs, issues, and maintenance of our projects. I think @debergalis is on top of making this happen.

**Comment by queso** [comment]
No, my concern is that MDG is the sole gatekeeper of important things and it seems like you guys are unwilling to cede some control into the community. I have heard @debergalis talk many times before about wanting to get the community more involved in finding solutions with both code and documentation.

I am all for helping, but I would like to have a structure that *trusts* at least some in the community to help with the gatekeeper process.

**Comment by stubailo** [comment]
@queso I've thought about this a fair bit, and I don't have an answer for you right now. The best I can say is let's figure things out as we go.

**Comment by queso** [comment]
@stubailo so as a guy who writes a lot of content, how do I participate best with this effort? Is my talent best applied to reviewing outlines and articles that you are working on, or can I add content of my own?

**Comment by stubailo** [comment]
@queso we're going to go through several stages of writing this thing, let me try to come up with the best ways to contribute for each. I think the initial version of the guide needs to be a somewhat consistent editorial effort, like a book would be, to set the tone and scope of the thing, so we are probably going to write the bulk of the content for the initial version for maximum efficiency.

These stages line up with the waffle board: https://waffle.io/meteor/guide?label=article

### Stage 1: Ideation

In this stage, we want to have an open discussion with everyone who cares to post on GitHub to make sure that we consider every possible idea. This is where we are trying to decide:

1. What should go in the guide and what the article breakdown should be
2. Which packages/tools we should recommend
3. Did we miss anything in our initial analysis
4. Do we need to write any code/modify any packages

I think you've been helping out a ton with this process by participating in the conversation and helping discover things we were missing in our original ideas.

### Stage 2: Outline

In this part, @tmeasday and I will try to condense all of the discussion into a complete outline of each article. As you can see in the waffle board, we have each assigned ourselves half of the articles, which we'll be shepherding through the process. You can see the first two outlines here: [Application Structure](https://github.com/meteor/guide/pull/56) and [Security](https://github.com/meteor/guide/pull/55).

The best way to contribute to this stage would be to help make sure that these outlines are good. That means:

1. They have all of the stuff from the discussion - we didn't miss any topics of importance
2. The order is good, and the organization makes sense
3. This is the right level of detail for a guide article

In general, what is blocking this outline from being a good foundation for a great guide article about that topic? Please **comment on the outline pull requests**.

### Stage 3: Example code

Next, Tom and I will collaborate on mangling the Todos example app to follow all of the recommendations in the guide. This is going to be crucial for understanding what it actually feels like to follow all of these recommendations. We need to find out:

1. Where do we need more guidance?
2. Where is there too much guidance, or the code becomes too heavy?
3. Are some of the recommendations inconsistent or incompatible?
4. Does this feel good?
5. Does it still feel like a "Meteor app"?

We haven't started on this yet, but it will probably involve creating a new repository. In that case, the best way to contribute will be to **file issues or PRs on the new Todos app to fix weird places**, and to file issues or discussions here where we uncover inconsistencies or problems.

After this stage, I think essentially all of the decision making will be done - once we have a complete set of outlines and a working example app, the rest is "just writing". So it's crucial that we get everything up to this point right, since this is most of the value of the guide for advanced developers. The rest of the process is just sugar, text, and examples.

### Stage 4: First draft

This point will require a consistent voice for each article, so each one will probably be written front to back over several large coffees by Tom and me.

After the first drafts are done, you'll be more than welcome to **submit pull requests to improve the writing**. Since the outline is previously agreed upon, we probably won't accept large reorganizations at this stage unless there is a serious issue.

We're also planning on hiring or contracting a technical writer at this point to go over everything with a fine-toothed comb to make sure it is nice to read, error-free, and understandable even to someone who isn't highly technical.

### Stage 5: Complete articles

At this point, the content is "done" - obviously we need a sustainable model for keeping it up to date and relevant, but I'll try my darn best to be proactive about accepting improvements. I hope that it will be much easier to contribute to the guide than the Meteor docs or any part of the codebase, since improving documentation is the easiest way to get started in open source.

We'll have an edit button on every page of the finished guide website, and hopefully we can set up a framework by which we can proactively seek out and accept contributions.

We also need to set up a framework to keep track of all community packages mentioned in the guide, and know whether they are up-to-date with new Meteor releases, so that we aren't recommending anything broken.

**Comment by queso** [comment]
For now I will continue to blog my content then. I will also make sure to look over the other pull requests, but I would really love to figure out how to involve more community into this community effort.

 I really appreciate the efforts and goals, I just don't want this to turn into another 'Ivory Tower' type project that excludes the community.

**Comment by stubailo** [comment]
> I just don't want this to turn into another 'Ivory Tower' type project that excludes the community.

Yes, you're absolutely right. I like to think that we are doing a better job so far than is average for a Meteor project.

Do you have any ideas specifically about what we should do to enable community contributions while maintaining a consistent vision/voice throughout? I guess the other question for me is, what is the benefit for you of having your content here, and not on your blog?

**Comment by queso** [comment]
> Yes, you're absolutely right. But I like to think that we are doing a better job so far than is average for a  Meteor project.

Yes, you are doing better than average!

> I guess the other question for me is, what is the benefit for you of having your content here, and not on  your blog?

I guess I just feel compelled to make the experience better for people who are getting started or diving a bit deeper into Meteor. The bigger we make the community, the better off all of us will be. A rising tide lifts all boats type-of-theory.

**Comment by stubailo** [comment]
> Yes, you are doing better than average!

I realize this isn't saying much since the average is not great at the moment, but we are trying our best.

@queso so most of my opinions on this are motivated strictly by making this the best possible experience for the readers. There are a few factors that lead me to believe that it is best for @tmeasday and me to write all of the content for the initial version:

1. Getting the initial version done as fast as humanly possible
2. Having a consistent "vision" for the whole thing, which is the reason we want to do all of the outlines first to make sure nothing is internally contradictory
3. We are working on this 9-5 full time, which is probably more time than anyone else is going to be spending on it, and thus it makes sense for us to keep some of the context in our head

However, there are a lot of things that are **real contributions** that will make the project happen much, much faster and have higher quality that don't involve actually writing text:

1. Identifying relevant community members for each topic, and inviting them to discuss the issues and suggest things that we are missing from ideas and outlines. This has been incredibly valuable to show the gaps in our thinking, and the faster we can get everyone talking about this stuff the faster we can move forward.
2. Applying a fine-grained comb to the outlines to make sure they cover everything that needs to be done.

> I would really love to figure out how to involve more community into this community effort.

What kind of involvement are you thinking of that we don't have at the moment?

**Comment by queso** [comment]
> What kind of involvement are you thinking of that we don't have at the moment?

Well, just like the TinyTest article that has been submitted. It looks like it needs work and I already have plenty of content on that subject from the book I was writing. Or the debugging article I wrote, I would love to expand that a bit and get it in as a guide.

Again, my motivation is to make the experience to leveling up as a developer with Meteor to as smooth as possible. If they hit too mnay walls, they leave. WIth this content being more official, I would love to help fill in the gaps. I think it would be silly for us to think that MDG has the corner on the 'Meteor knowledge market'. Plenty of people in the community have *more* experience building applications with Meteor and are good at writing. Let's get those people excited and involved, imo.

**Comment by stubailo** [comment]
> Well, just like the TinyTest article that has been submitted.

There's a comment thread there, and I think the conclusion is that this is great content but doesn't belong in the guide. I believe this kind of curation is crucial for this project to be a success. There are already some community wikis, I don't know that this project needs to be a wiki as well.

> I think it would be silly for us to think that MDG has the corner on the 'Meteor knowledge market'. Plenty of people in the community have more experience building applications with Meteor and are good at writing.

Yes, I 100% agree. But I don't think sending PRs with entire articles is the best way to do that. My current belief is that the best role for MDG to play in this process is as a curator of the community experience building apps. That implies that we should look for this knowledge wherever we can find it, which we have been doing our best at - perhaps we could be doing a better job at this?

> Let's get those people excited and involved, imo.

What I'm getting here reading between the lines, is that the best way to get people excited is to accept contributions of large chunks of content. However, _nobody_ is going to be contributing unreviewed large chunks of content. Even the stuff I write is going to be thoroughly dissected by @tmeasday, and based purely on community-sourced ideas through discussion on this repository.

**Comment by queso** [comment]
> I believe this kind of curation is crucial for this project to be a success. There are already some community wikis, I don't know that this project needs to be a wiki as well.

I believe this is a core piece of the real issue here. There is a piece of technology created and used by the MDG, but this curated guide won't talk about it? As a community, if we don't press for something about testing in this doc, I believe we have failed and done a disservice to developers and the larger Meteor community. Testing is important. I don't want to disgress this thread into talking about testing itself, just pointing out that the community is already surfacing a weak point that is being left out of this guide.

> Yes, I 100% agree. But I don't think sending PRs with entire articles is the best way to do that. My current belief is that the best role for MDG to play in this process is as a curator of the community experience building apps.

The original core question is about the Governance process to let people work within this framework as a way to contribute. I still feel like the answer is 'Just review what we are doing and that is a big help'. That isn't how Rails Guides work...

> That implies that we should look for this knowledge wherever we can find it, which we have been doing our best at - perhaps we could be doing a better job at this?

I am not looking for you to do a better job at pinging people to review outlines and finished writing. I am looking for you to work on *Meteor core code* and just help push a concentrated community effort forward. It isn't feasible to only have MDG paid employees writing blessed documents to help the community.

> What I'm getting here reading between the lines, is that the best way to get people excited is to accept contributions of large chunks of content. However, nobody is going to be contributing unreviewed large chunks of content.

Yeah, stop that. Nothing is implied here, other than I want to speed up this process and take some of it off MDG core. To be fair, this isn't the first time this type of project has been attempted internally. If we want to be modelled after successful external open source projects, maybe we should try to understand what works and what doesn't? I only see one Rails core member in the list of authors: http://edgeguides.rubyonrails.org/credits.html.

Also, I have plenty of people such as @sachag and @dweldon review my posts before they go out, I am not asking for unreviewing content to be published directly, I just want to evenly spread the load amongst people who are willing to help with more than just reviewing outlines.

**Comment by queso** [comment]
Please take all this with a grain of salt, I am not trying to argue a bunch here, just trying to figure out how to push past a two man team of writers to build something great. I think this is all a great start, so don't get discouraged.

**Comment by stubailo** [comment]
> As a community, if we don't press for something about testing in this doc, I believe we have failed and done a disservice to developers and the larger Meteor community. Testing is important.

I couldn't possibly agree more. Have you seen this discussion? https://github.com/meteor/guide/issues/20 I do strongly believe that having TinyTest at all is insane and that we should get rid of it as soon as humanly possible in favor of some testing library that people outside of the Meteor world actually use.

> I still feel like the answer is 'Just review what we are doing and that is a big help'. That isn't how Rails Guides work...

Do you have a concrete proposal for a different process which will produce higher quality content, or get it done faster?

> It isn't feasible to only have MDG paid employees writing blessed documents to help the community.

If you pass me along some documents, I will find a way to bless them. The whole point of this project is to produce specifically those blessed documents, because we did such a terrible job before.

> To be fair, this isn't the first time this type of project has been attempted internally.

I think it is, based on my analysis of the situation - if you're referring to the Meteor Manual, that was a completely different thing.

Let's think about something else for the second.

-----------

If you could have the keys to one of the proposed articles, which one would it be?

**Comment by queso** [comment]
Too many to choose. #10, #35, #40, #33, and #36 all look interesting to me. I also think we should have an article about debugging and will add a suggestion for it.

**Comment by queso** [comment]
@stubailo thoughts?

**Comment by stubailo** [comment]
Hey, we're working on it - can I get back to you on Monday?

**Comment by queso** [comment]
Sure

**Comment by stubailo** [comment]
So I've talked to @tmeasday, and we think it would be awesome to collaborate on an article. I think the suggestion you had for the debugging article would be a great place to start, since it's a really good idea that we should have, and it's not yet integrated into our current schedule.

I've added the `article` label to the issue you filed, so it will now be tracked in our waffle board here: https://waffle.io/meteor/guide?label=article

Let me acquaint you with the article plan:

1. Ideation - write down the major design decisions and ideas for the article, and loop the relevant people into the conversation (these could be people who have written articles about Meteor debugging, for instance)
2. Outline - write a fairly detailed outline that covers the major decisions and sections of the article. Someone reading this should be able to get a pretty good idea of what the final article will look like in their mind.
3. Code examples - this means updating the todos app, and writing some code snippets to back up the outline. Ideally, we would get all of the code examples we are planning to use in the final article here, but that's probably not possible.
4. Rough draft - write the actual article

To get this article in the initial guide publication, which we hope to release sometime before the end of the year, Tom and I estimate it would be good to have an **outline for the debugging guide in two weeks** - this means about a week for discussion in the ideation stage and about a week for writing and reviewing the outline.

What do you think? Are you in?

**Comment by stubailo** [comment]
Thoughts, @queso?

**Comment by queso** [comment]
Yip, in.

**Comment by stubailo** [comment]
Awesome, looking forward to your ideas about debugging!
