### ISSUE TITLE
Make edit on github link more prominent

### ISSUE THREAD

**Issue by stubailo** [meteor/guide#207]
It would be clearer that we are looking for improvements, and that this is an open-source document, if you could see the edit on github link near the top of the article.

**Comment by stubailo** [comment]
Suggested by @rgoomar.

**Comment by rgoomar** [comment]
Maybe you could do a banner-type situation like open source GitHub pages do. Just a thought.

**Comment by stubailo** [comment]
Got a link to a good one?

**Comment by rgoomar** [comment]
Banners:
https://github.com/blog/273-github-ribbons (something similar)

Or even a nice big link at the top like RoR does:
http://rubyonrails.org/

There is space in the fixed banner. I know you guys want to add search capability to that, but a button to also go to contribute would be awesome. And what would make it even better is to allow you to go directly to the file so you can hit the "edit" button on GitHub and get going immediately for a PR.

**Comment by stubailo** [comment]
Yeah the button at the bottom goes directly to the file, I think that's better than just linking to the repo.

**Comment by mitar** [comment]
I think it is good as it is.

**Comment by stubailo** [comment]
@mitar one concern I have is, we don't have a good way of getting feedback from people about which parts are hard to understand. any ideas about that?

**Comment by mitar** [comment]
I do not think you will get it through GitHub **editing**. That is a different feedback you need. Editing is for people who see something wrong and know and want to fix it. What you are saying is that we should also have some feedback mechanism for people who are unsure: or they think something is unclear, have questions, or just are unsure of the fix and would like first to discuss it a bit (imagine talk page on Wikipedia).

I really loved how Django has the feature of per-paragraph comments for [their guide](http://www.djangobook.com/en/2.0/index.html). Just from number of comments per paragraph you could see where are problematic parts. Sometimes you could get answers from the discussion from other people, even before the fix was integrated into the guide. They do not have it anymore with the latest version (linked above) though. I think because they were using some external libraries for that. See [how valuable comments were](https://github.com/jacobian-archive/djangobook.com/blob/e39a02a405c2f7fad1164bbd0b88b1b6c39bd587/frontmatter.rst#acknowledgements).

These days, I would suggest that you simply integrate [Hypothesis](https://hypothes.is/). It is a commenting system which allows highlighting and annotating parts of the page. Just add load it on the site and this should be it.

**Comment by rgoomar** [comment]
@mitar I see what you are saying, but I think it is different than the goal of this issue. It is so that people can get to the GitHub edit page to make a quick modification. Right now, if the section of the guide is long, they have to go all the way to the bottom to go to the GitHub editor directly. It's about getting faster feedback and fixes, so having it in a fixed position so that at any point you can click it no matter where you are on the page would be a nicer UX. 

But, I really do like the idea of having per-paragraph comments or something similar. That allows for a more deeper set of changes to the guide, but that could also be achieved with issues linking to the lines.

**Comment by mitar** [comment]
> Right now, if the section of the guide is long, they have to go all the way to the bottom to go to the GitHub editor directly. It's about getting faster feedback and fixes, so having it in a fixed position so that at any point you can click it no matter where you are on the page would be a nicer UX. 

Sorry, but for somebody who wants to go through the whole process of editing and fixing it, I do not think that finding a link at the bottom (it is really easy to scroll to the bottom quickly) is so hard or time consuming. Sorry, for me this looks like premature optimization. Most people will not be editing. And those who will have a known location to the edit link, at the bottom. Go there, click, edit.

**Comment by stubailo** [comment]
Yeah, we should talk about comments in a different issue. Sorry for bringing it up.

**Comment by stubailo** [comment]
(There's a link at the top now)
