### ISSUE TITLE
Creating custom Accounts authentication

### ISSUE THREAD

**Issue by rclai** [meteor/guide#223]
`accounts-base` allows us to create custom authentication methods via `Accounts. registerLoginHandler`, like logging in with different kinds of data. It would be nice if there was a guide that showed, for example, how to log in with your phone number.

**Comment by stubailo** [comment]
Ah, looks like @robfallows has created this: http://robfallows.github.io/2015/12/17/writing-an-oauth-2-handler.html

But I failed to take a look at it. @rclai does this cover your need? Or is there something else?

I agree we should have a section in there about extending the accounts system with more handlers since it's something lots of serious devs need to do.

**Comment by rclai** [comment]
Okay, I'll take a look, thanks.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

We are going to make many updates to the guide in the next weeks and it's better to focus on issues with recent activity. If you think this issue is still relevant please open a new one.
