### ISSUE TITLE
Structure Section - Sharing Code Question

### ISSUE THREAD

**Issue by dcworldwide** [meteor/guide#250]
After reading the Sharing Code section of the https://github.com/meteor/guide/blob/structure-content/content/structure.md page, I didn't understand whether I can use es6 import syntax to import code from my local packages directory `/packages`.

Is this directory a special directory just like `/imports`? From a es6 import / export perspective, do they behave the same way? Or are local packages eagerly loading into the global namespace as per Meteor 1.2?

**Comment by tmeasday** [comment]
Hi @dcworldwide -- you import them with `import .. from 'meteor/package-name'` as mentioned here: https://github.com/meteor/guide/blob/structure-content/content/structure.md#importing-from-packages

I'm sort of unclear about the question here? Is there somethine we could make clearer? Is it the fact that local packages and Atmosphere packages are treated the same in this respect?

**Comment by dcworldwide** [comment]
I think the subtlety between the different package types confused me. 

From my understanding, we have:

1. npm -install(ed) packages
2. Atmosphere installed packages and;
3. local user created packages defined in /packages. (Are these only npm packages at 1.3?)

I didn't realize from the a https://github.com/meteor/guide/blob/structure-content/content/structure.md#importing-from-packages how packages of type 3 worked.

**Comment by dcworldwide** [comment]
HI @tmeasday , To help you better understand my scenario, here is the problem i'm trying to solve as I read this section of the guide.

I have a meteor app with a large number of local meteor packages. Now I need to write back-end meteor apps that share code with the web app. At 1.3, I want to learn how I can:

- Move those packages out of my web app and into a common location so that I can share those packages across my front end and back end meteor apps. 
- Make those packages as npm compliant as possible (if this is the recommendation...)
- Still have inter-dependencies between those packages. I.e. I have a schema package, that is used by a collection package, which is then used by a collection-methods package. 

This section is great so far, but i feel like there are opportunities for the guide to be more explicit for those of us that need a bit more hand holding.

**Comment by tmeasday** [comment]
> local user created packages defined in /packages. (Are these only npm packages at 1.3?)

If they are in `/packages` they are "Atmosphere" packages (the naming is confusing here. I call them "atmosphere" packages so that it's clear that Meteor works with both those packages and NPM packages).

> This section is great so far, but i feel like there are opportunities for the guide to be more explicit for those of us that need a bit more hand holding.

I think I'd recommend just putting code into various modules in your apps that import each other (I'm assuming this code is private and you don't want to share it with the world). You can include the same code in each app by using a git submodule or by putting all of your apps in the same repository.

Does that make sense?

**Comment by skirunman** [comment]
We also have a bunch of local packages we developed to solve issue of not bringing in unwanted code to our two separate meteor client apps for web and mobile. From what you said about it sounds like you are saying the recommended approach with Meteor 1.3 is to move these local packages to es6 modules and use import/export. Is this correct or did I mis-read what you said above?

Because in the guide you say:

> If you want to create Meteor applications with separate code, you are best sharing the code via a package system---either Meteor's package system or NPM. The easiest way to do this is to factor code that you'd like to share out into a Meteor package and add it directly into the app by placing it in the application's local packages/  directory.

I asked a related question https://github.com/meteor/guide/pull/226#issuecomment-190409787 with regards to using PACKAGE_DIRS when you want to share code (packages or modules) between two different Meteor apps. I guess I'm asking for a bit more clarification on best approach to share code between two different Meteor client apps that share a common Meteor server.

**Comment by tmeasday** [comment]
You're right, that section of the guide is not consistent with the advice above. I'll change it to recommend using modules. Does that make sense to you @skirunman?

**Comment by skirunman** [comment]
Sure, just looking for guidance and I can buy in to the "use modules for all shared code and publish code on NPM" approach going forward.

**Comment by dcworldwide** [comment]
Thanks @tmeasday 

`If they are in /packages they are "Atmosphere" packages (the naming is confusing here. I call them "atmosphere" packages so that it's clear that Meteor works with both those packages and NPM packages).
`
Hmm I can see your point. HoweverI still  find the nomenclature confusing. I.e. from my pov atmosphere is a package server, so a local meteor package that is never deployed to atmosphere shouldn't be considered an atmosphere package. Others may have a different view...

`I think I'd recommend just putting code into various modules in your apps that import each other (I'm assuming this code is private and you don't want to share it with the world). You can include the same code in each app by using a git submodule or by putting all of your apps in the same repository.`

That does make sense. I see there is a bit of debate going around regarding submodules vs npm link.... would be nice if the docs closed off on that debate too.
