### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by tmeasday** [meteor/guide#36]
### Article outline

https://github.com/meteor/guide/blob/master/outlines/security.md

### Major decision points

1. The security surface area of your app is:
  1. DDP - user login, methods, and publications
  2. Source code files served by Meteor
  3. Any HTTP endpoints you have
2. Use Meteor methods, not allow/deny, so that you can understand the attack surface of your app better
3. Methods and publications should never accept generic black-box objects as arguments, you should know exactly what the properties are on every argument
4. App secrets should be passed in through `Meteor.settings`
5. SSL is a must-have for any app
6. We have a security checklist, there are lots of points in there

**Comment by stubailo** [comment]
The initial outline:

### Meteor guide: Security

Meteor apps can be very easy to secure if you follow a few simple principles, and there are some packages that streamline the process for you.

1. The security surface area of a Meteor app
    1. Methods
    2. Publications
    3. Served files
2. How to set up roles and permissions for user accounts
3. How and why to use SSL
4. How to manage sensitive API keys and configuration
5. Common mistakes and misconceptions

**Comment by stubailo** [comment]
Securing a Meteor app can actually be quite simple if you understand the possible attack surface. Part of good security practice is to minimize that surface and make sure every input is what your expect it to be.

#### No allow/deny

This guide will focus on methods only, rather than doing mutations from the client and attempting to validate them with rules. This limits the possible attack surface area of the app, and will tie together well with what we want to do for forms: #29 

Fun article: https://www.discovermeteor.com/blog/allow-deny-challenge-results/

#### alanning:roles

We'll probably recommend this for managing user roles, unless something else comes along.

https://github.com/alanning/meteor-roles

I don't think we can use ongoworks:security because it seems fairly tailored to the allow/deny model of things.

#### Managing API keys

Probably Meteor.settings is the correct way to do this. We should document some principled ways of managing settings between development/test/staging/production environments. Perhaps this is just recommended naming for the files.

How does this interact with environment variables? Perhaps the Meteor tool should let you pass env vars in Meteor settings?

#### Common mistakes

- insecure/autopublish (aaaaaahhhhhhh I hate insecure personally.)
- Not filtering fields in publications
- Publishing user documents with sensitive data, like hashes or keys
- Not doing security in data fetched inside methods - don't let method side effects expose data
- Use specific selectors
- Securing the route and not the data being sent
- Don't ever ever trust the client - note that all the code you write can be called trivially from the browser console
- Always check types everywhere with simple-schema
- Don't use user profile, ever
- Be careful about `{{{ .. }}}` when printing HTML to the page. don't use it unless you really absolutely have to
- **Anything else?** I tried to scour online sources for this stuff, the above is all I found.

**Comment by stubailo** [comment]
One more thing: audit argument checks. We should see what that looks like in a world where we use simple schema to validate method args.

**Comment by stubailo** [comment]
@queso any thoughts on what other important stuff we should include? I know you've written a fair number of posts about these topics.

**Comment by queso** [comment]
Looks like you covered anything I can think of right now. I also have this checklist that covers articles already written on many of these topics by the community: https://meteorjs.club/MeteorSecurityChecklist.pdf. Mostly myself, @pcorey, and @dweldon. Maybe they have thoughts to add?

**Comment by queso** [comment]
Actually, in reading the bit about Meteor.settings, you can already pass METEOR_SETTINGS to a Meteor app to set it. I would avoid talking about per environment files because I think it is dangerous to check those files into source control. 

The guides should heavily advocate that people using Meteor.settings for API keys and various runtime settings so that is can be controlled per environment and you can secure it by using environment variables.

**Comment by queso** [comment]
I also agree that we should advocate for methods over allow/deny, perhaps it is worth talking about the dangers of Allow/Deny based on @sachag's post on Discover Meteor?

**Comment by queso** [comment]
I would also add that there is nothing wrong with user.profile, I actually use it and like that it is published with user records for you. We just need to explain that it should be locked down or the developer should be aware the users can change it by default.

**Comment by pcorey** [comment]
@stubailo This is an awesome project!

A few thoughts on security things.

***

Collection validators (allow/deny) can be a little harder to think about, but I don't know if I'd advocate completely avoiding them. If you [whitelist the modifiers](http://blog.east5th.co/2015/06/15/allow-and-deny-challenge-check-yourself/) you accept within an allow/deny, and assuming you understand the 1-pass rules of allow & deny, you should be pretty well off. Accepting random modifier object into methods can be [more dangerous](http://blog.east5th.co/2015/10/19/rename-your-way-to-admin-permissions/) than using collection validators because `$rename` is allowed in that context.

The bottom line is that ___a lot of apps___ use allow/deny rules because they fall in line with Meteor's much-hyped "DB everywhere" way of doing things. Not acknowledging that as an attack vector may lead to misunderstandings.

***

Not using profile ___ever___ is a bit much. Just be aware that profile is writable by clients by default. That default can be changed if needed.

***

One note about browser-policy is that CSP [isn't supported on all browsers that Meteor supports](http://caniuse.com/#feat=contentsecuritypolicy). This might lead people to thinking it's a silver-bullet for XSS across the board, when it's actually not. IMO, you should only rely on browser-policy as a last line of defense, not your only means of protection.

***

One more small thing is to always use `this.userId` on the server, rather than trusting a user provided userId or user object. That can lead to [all kinds of issues](http://blog.east5th.co/2015/05/05/meteor-security-in-the-wild/).

***

Josh's checklist is a good summary of all of this stuff.

At the end of the day, I wouldn't advocate avoiding certain pieces of the stack (validators, profile, triple brace template tags, etc...), I would just try to emphasize what they do and what their dangers are. The only way to really build a secure app is to understand all of this stuff, not to avoid it.

Thanks for all the hard work you're doing with this project!

**Comment by pcorey** [comment]
Also, I'll plug a couple of my security-centric packages that might help some people out.

[`east5th:check-checker`](https://github.com/East5th/check-checker) is a static analysis tool that checks for methods and publications that are missing `check` calls on their arguments. It's a good compliment to `audit-argument-check` which does runtime checks of the same thing.

[`east5th:package-scan`](https://github.com/East5th/package-scan) is a community driven repository for Meteor package security issues. You can either add the package to your project, or use the [web tool](http://scan.east5th.co/) to find out if your project is using any packages with known security issues.

**Comment by stubailo** [comment]
> I would just try to emphasize what they do and what their dangers are. The only way to really build a secure app is to understand all of this stuff, not to avoid it.

I think we aren't going to avoid mentioning those things at all, just strongly caution people that you really need to know what you're doing when you are using things like `{{{ ... }}}`.

> Not using profile ever is a bit much. Just be aware that profile is writable by clients by default.

The thing about profile goes with some musings in the Accounts #35 section about suggesting that people should use a separate `UserProfile` collection instead of attaching extra properties directly to the user object. This is the easiest way to avoid publishing some secret keys to the client by accident. Plus, it makes you more future proof against future changes to the accounts system. If you don't think this is a good approach, let's discuss on the other thread.

> Accepting random modifier object into methods can be more dangerous than using collection validators because $rename is allowed in that context.

My thought process about Methods is that they _should not_ be generic. You shouldn't have a method called "updateProfile" that just accepts a random modifier object. It should accept a set of keys and values, and the keys and values should all be validated both on the server and the client. Ideally, `$rename` is not one of the keys allowed in your profile object ;]

The problem with allow/deny is in part that it's super hard to validate anything based on an arbitrary Mongo update query; I think the solution is to simply not send Mongo modifiers over the wire by writing specific methods.

**Comment by stubailo** [comment]
@queso great tip on the security checklist! I think having such a checklist in the guide would be bomb. Also, makes me think we should have a citation system when we "rip off" good content like that, it would be a shame for you to not get credit for compiling that list, and for the authors you cited as well. I wonder what that would look like - footnotes?

**Comment by stubailo** [comment]
Starting work on a final outline here: https://meteor.quip.com/xXRRA7aqTbLX

**Comment by stubailo** [comment]
Just posted the proposed outline as an edit to the first comment above: https://github.com/meteor/guide/issues/36#issuecomment-149108396

This is a pretty sensitive topic, let me know if this is good, if I missed anything, and if it seems like a good order for the content.

**Comment by stubailo** [comment]
Moved the outline to a PR: https://github.com/meteor/guide/pull/55

Please comment there!

**Comment by rclai** [comment]
Can I get a definite confirmation from MDG that we _should_ be using `this.userId` for publications _and_ methods? I keep seeing people saying use `this.userId` on publications and `Meteor.userId()` on methods, which is really really annoying.

**Comment by queso** [comment]
I think the issue might be around this.userId() on the client vs server for
methods?

**Comment by stubailo** [comment]
Inside methods, they are basically identical. I think it would make sense to suggest that people use `this.userId` for both, since the opposite is not possible.

**Comment by dweldon** [comment]
I think `this.userId` is the preferred way to go, __however__, we use `Meteor.userId()` in our methods because it's easy to stub in tinytest. It may be that with some of the velocity frameworks this is a non-issue. Testing experts feel free to chime in here.

**Comment by alanning** [comment]
I could write about authorization if that would be useful?  Not sure where to do that tho.  Should it be a PR?

Authorization is not covered in the [current version](http://guide.meteor.com/security.html) of the guide but I see you already have a "Roles and permissions" section in the [security outline](https://quip.com/xXRRA7aqTbLX) which mentions [`alanning:roles`](https://github.com/alanning/meteor-roles).  That roles repo also has [example apps](https://github.com/alanning/meteor-roles/tree/master/examples) for each router, including two for flow-router which may be useful for people.

**Comment by stubailo** [comment]
I'm thinking of explaining roles more fully in the article about user accounts - there's a PR open for that now. It would be great to include some content from you about recommended usage! Mostly it should just be a summary and then a link to your docs probably

**Comment by avalanche1** [comment]
http://guide.meteor.com/security.html#allow-deny
I thought that removing 'insecure' package prevents any clientside access to DB (except for updating user profile which is cured by `Meteor.users.deny(update: ->true)` - was I wrong?
Current guide text makes me feel like I need to explicitly write 
```
Lists.deny({
  insert() { return true; },
  update() { return true; },
  remove() { return true; },
});
```
for each collection I have.

**Comment by stubailo** [comment]
@avalanche1 the intention is that this code prevents other code from later calling allow. I think it says that in the text somewhere. Ideally it would be possible to remove the `allow`/`deny` functionality altogether, but that work isn't done yet (I got started on it but didn't get a chance to finish).

**Comment by avalanche1** [comment]
Well, this text looks confusing. It should say that if you remove 'insecure' and don't explicitly specify allow\deny rules - client won't be able to modify anything.
