### ISSUE TITLE
Fastosphere

### ISSUE THREAD

**Issue by gregorybleiker** [meteor/guide#409]
The guide mentions fastosphere on http://guide.meteor.com/using-packages.html. The link is also broken, I guess this has to do with the meteorapp site closing down. I could not find any replacement url.

**Comment by lorensr** [comment]
There was some talk of putting important community apps on galaxy for free?
I'd include this and useraccounts

**Comment by stubailo** [comment]
Yeah I think we offered but some people didn't take us up on it. Pinging @splendido from useraccounts; who owns fastosphere?

**Comment by lorensr** [comment]
@acemtp I used to have your app open all the time, and I miss it 😢😊

**Comment by acemtp** [comment]
Hey @stubailo, I'm the creator of Fastosphere 😄 , the same who create Talkus.

If I can have a free galaxy to host it, I'll be happy to do it.

**Comment by stubailo** [comment]
@acemtp can you email Mark Trang? Just asked - he'll get you set up with a container for fastosphere! Let me know if you don't have his email address.

**Comment by splendido** [comment]
Hey @stubailo, I got the email about _Galaxy Package Demo program for Meteor community packages_ and deploied [useraccounts-bootstrap](http://useraccounts-bootstrap.meteorapp.com/). Useless to say, this first experience with Galaxy was great! :-)

There are quite a number of packages under `useraccounts` namespace and one container is not enough to host them all... (Btw, there's also `splendido:useraccounts-meld` which might deserve its own container...).

I wrote an email to Rohit Bakhshi on the 23th of March about this ans see whether there could be interest in providing a couple more containers for useraccounts or not, but so far got no reply.

If yoo think I should use the one container for the _useraccounts' home page_ rather than for a single package showcase, just let me know and I'll be happy to switch over.

**Comment by stubailo** [comment]
Hmm the home page is the only one I've ever visited, I didn't know there were any other demos. Not sure what to do in the case where one container is not sufficient for demos - it seems like in terms of resources it should be but its not convenient to host different demos in one meteor app.

**Comment by splendido** [comment]
The thing is the home page was just a landing page not actually demoing any package.
So I deployed the demo for the most downloaded package which I thought was more in line with the purpose of the demo program.

...and yes, one container might be enough to serve many simple demo apps, but trying to deploy a second one ends up with an error saying there are no free container left.

**Comment by acemtp** [comment]
Here it is! http://fastosphere.meteorapp.com

Sadly all old links (fastosphere.meteor.com) will not work anymore.

Thank you mdg for the hosting

**Comment by stubailo** [comment]
@acemtp we can set up a redirect!

**Comment by acemtp** [comment]
@stubailo a link on how to do that?

**Comment by stubailo** [comment]
I think you have to talk on Mark Trang, just pinged him.

**Comment by lorensr** [comment]
@stubailo can we get one more container for @splendido so we can have at least one example, along with the homepage working? (or one container for each, if there's a way to do that cheaply. `.05` ECU ☺️)

**Comment by DylanKojiCheslin** [comment]
Just tested the link, it works. Should this issue be closed?
