### ISSUE TITLE
Advanced: Deployment, monitoring and analytics

### ISSUE THREAD

**Issue by tmeasday** [meteor/guide#44]
## Outline

1. Thinking about deploying a web application
 - Staging vs Production
 - Secrets etc 
 - Acceptance tests

2. Deployment options
 - Deploying to meteor.com (free)
 - Deploying to modulus
 - Deploying w/ mup
 - Deploying to Galaxy

3. Monitoring your users
 - Integrating with popular analytics platforms to track method calls, publications, and URL hits

4. Monitoring your production app
 - w/ Galaxy
 - w/ Kadira

5. Deploying new versions
 - how HCP works with rolling updates

6. Load testing your application (?)

**Comment by tmeasday** [comment]
@stubailo did you have thoughts on any of this?

Specifically:

1. Should we explain / sketch how to deploy to all of those options? Or just mother + galaxy?
2. Do you think we should talk about load/stress testing here, or in the testing chapter?

**Comment by queso** [comment]
I think the CDN webprefix stuff should be talked about here too, using a CDN should be a best practice and it took me much longer than I wanted to get right with Crater.io.

> 1. Should we explain / sketch how to deploy to all of those options? Or just mother + galaxy?
> 2. Do you think we should talk about load/stress testing here, or in the testing chapter?

To your questions @tmeasday, I think the community would be happy to contribute on #1 for other platforms. Not many could write about Galaxy atm, so that is best left to you guys. On #2, I would think that could be a full blown article of it's own or should live under testing, imo.

**Comment by queso** [comment]
On second thought, maybe the CDN stuff is better to be in the core docs, people will look there first.

**Comment by stubailo** [comment]
> CDN stuff is better to be in the core docs, people will look there first.

My opinion is that it's hard to find relevant info in the core docs. Hopefully people will think "I'm running an app in production, better read the part of the guide about running production apps" and that will talk about CDN.

**Comment by tmeasday** [comment]
Thanks for mentioning CDNs @queso it had completely slipped my mind. Also SSL.

**Comment by tmeasday** [comment]
Also add something about "micro apps". Probably talk about migrations again here as well.

**Comment by queso** [comment]
Np, I have a blog post covering some SSL and am working on one for CDN. My CDN blog post will cover using cloudfront and the web prefix stuff.

**Comment by tmeasday** [comment]
Ok, I'll look forward to your notes

**Comment by tmeasday** [comment]
Hey @queso I wonder what you mean by "CDN webprefix" I wonder?

**Comment by tmeasday** [comment]
PR: https://github.com/meteor/guide/pull/74

**Comment by itamaro** [comment]
Some more related topics I'd like to see here: 

- deployment to self managed environments
- deploying from CI server
- integrating meteor in a microservices architecture (not sure if should be here, or its own guide)
- meteor and docker
- integrating with common logging, monitoring, analytics stacks
- configuring meteor to work behind a proxy, a load balancer,  maybe with SSL termination, maybe with SSO authentication gateway, maybe with multiple URLs pointing to the same app

Disclaimer: I just started playing with meteor, so I don't know much yet. These are things that I consider relevant coming from other stacks, so I figured some will apply here.

**Comment by tmeasday** [comment]
Thanks for your comments @itamaro 

> deployment to self managed environments

We do talk about deploying to Digital Ocean w/ mup. does this cover this use case?

> deploying from CI server

It might be good to have something about this but I've not done it before. Perhaps someone can send a PR with some content?

> integrating meteor in a microservices architecture (not sure if should be here, or its own guide)

Yeah I suspect this'll end up being it's own article. We should probably touch on it here but I'm not quite sure what to say.

> meteor and docker

I think the picture here is still unclear maybe? The development version of MUP (mupx) is using docker. Perhaps it'll just be an upgrade of that section to cover it off. Or is there more detail you wanted here?

> integrating with common logging, monitoring, analytics stacks

We've got analytics covered. Monitoring we've covered Kadira (a Meteor-specific APM soluiton). Are there particular services you'd cover for logging / monitoring?

> configuring meteor to work behind a proxy, a load balancer, maybe with SSL termination, maybe with SSO authentication gateway, maybe with multiple URLs pointing to the same app

I think this is probably out of scope. MUP does all this and is open source, so my suggestion for people that wanted some guidance on how to roll their own would be to check out what's it's doing and start from there. 

I'm not sure though. @zol I think we discussed at some point the possibility of recommending a load balancer (haproxy?) and potentially even publishing a "working" config.

**Comment by itamaro** [comment]
My pleasure :-)

I wasn't familiar with mup. From a quick look, this should be a good starting point for other self-hosted cases (on-premise servers, or other IaaS-based offerings). I guess users can contribute provider-specific examples (e.g. "this is how we do it with AWS / GCE / ...").

About CI - I'm sure CI vendors will be glad to promote their products by contributing articles on how to use their products to deploy meteor ;-) (I never done that with Meteor as well)

re. Docker, these days it almost doesn't make sense to deploy without containerization, image registry, and container orchestration. if mup does it all inside, then cool. but I suspect there's more to cover (probably things that whoever built Galaxy went through), like dev/stage/prod management (e.g. docker compose vs. actual deployment to whatever-container-engine), how to plug-in configuration (where's mongo, what's the root URL), and what base images to use for what use-cases.

re. logging / monitoring - I was thinking about the self-hosted case, where I own the whole stack, and I don't want to rely on external SaaS for logging / monitoring. e.g., how to integrate with logstash / kibana / statsd / graphite / ...

you said that mup is a good reference for people that want guidance on how to roll their own. so this means that the scope of this guide is "Deployment, Monitoring, and Analytics *for selected hosting providers*" ? because this is a pretty different title for such a guide. my initial expectation from the original title is to deal mainly with the case of rolling my own thing.
