### ISSUE TITLE
About the guide's usability.

### ISSUE THREAD

**Issue by 7immy** [meteor/guide#463]
I'm really excited about the guide :) It seems to be getting lots of updates and now has some really great tips and examples in there! Thank you sooo much guys! :)

That said it is starting to get quite hard to read the pages and effectively navigate the sidebar as more and more topics and sub topics are added and each page is getting longer and longer.

I had a few UX/UI and style ideas that may help below:

**Sidebar**
- The old guide's sidebar highlighted the active heading that the user was currently looking at. It would be great to have this back again as it was really helpful for navigating through a long page.
- More padding above and below subsections might help the sidebar visually.
- Perhaps moving the sub levels of the sidebar to the top of the relevant page would be easier for the user to navigate?
  - see here for an example: https://laravel.com/docs/5.1

**Pages**
- The page titles could do with either being LARGER or **bolder**, especially for h3 titles. The hairline font currently "_disappears_" if the user is scanning and scrolling the page while trying to quickly find a section.
- More spacing above h2 titles could help to define a new section better for the user.
- Making the left anchor icon red next to each h2 heading would help users quickly identify the different sections while scrolling down the page.

Just some thoughts,
Thanks for reading :)

**Comment by tmeasday** [comment]
Should we move this to hexo-theme-meteor?

**Comment by tmeasday** [comment]
I think the first point is actually a bug, looking at it now.

**Comment by lorensr** [comment]
Active highlighting is dup of https://github.com/meteor/hexo-theme-meteor/issues/10

Unless it's hard for you/dom to track, I'd prefer just pointing in the readme to hexo-theme, but not going through the hassle of moving the issues that get submitted here/docs anyway. But if you'd like, I can start doing that.

**Comment by 7immy** [comment]
Sorry guys, didn't know about the hexo-theme-meteor repo.

**Comment by tmeasday** [comment]
@7immy - why would you? :)

**Comment by 7immy** [comment]
Good point :)

**Comment by lorensr** [comment]
Thanks @7immy for the suggestions :) Here are my thoughts on two of them:

### Page ToC

> Perhaps moving the sub levels of the sidebar to the top of the relevant page would be easier for the user to navigate?
see here for an example: https://laravel.com/docs/5.1

On mobile, since the menu is hidden, I would like to see the page's ToC duplicated at the top of the page. 

You think it's important on desktop as well? I can see the ToC fine in the menu:

![image](https://cloud.githubusercontent.com/assets/251288/15485657/8ca7f37a-210e-11e6-90e3-1371a8024cb6.png)

### Scrolling down pages

I identify with the difficulty in scrolling down a page scanning headers. Especially looking for an API function. If I start at the top of

http://docs.meteor.com/api/collections.html

and start scrolling down looking for insert, it doesn't pop out at me:

![image](https://cloud.githubusercontent.com/assets/251288/15485871/de985700-210f-11e6-8215-d5bc804d2c43.png)

Partially because it's in the middle of `Mongo.Collection#insert(doc, [callback])` and partially because it's inside the api block, which feels to me similar to a snippet or an aside, whereas I'm looking for something more like a normal `<h#>`, like `Match Patterns`:

![image](https://cloud.githubusercontent.com/assets/251288/15485963/6df1b31a-2110-11e6-981e-89a5a188dc63.png)

> Making the left anchor icon red next to each h2 heading would help users quickly identify the different sections while scrolling down the page.

At one point all the header anchor icons were red, and I didn't like it on pages like this with a few headers in view at once:

![image](https://cloud.githubusercontent.com/assets/251288/15485731/f827c152-210e-11e6-8869-63d795249c7f.png)

I think a darker gray or red just on the h2s would help me have a sense of structure level.

**Comment by dominicnguyen** [comment]
Cheers @7immy for the collated feedback it really does help us move quickly on improvements. Thank you!

These are done:
- [X] The page titles could do with either being LARGER or bolder, especially for h3 titles. The hairline font currently "disappears" if the user is scanning and scrolling the page while trying to quickly find a section. (made headings larger)
- [X] More spacing above h2 titles could help to define a new section better for the user. 
- [X] Making the left anchor icon red next to each h2 heading would help users quickly identify the different sections while scrolling down the page. (made it darker grey per @lorensr suggestion)
- [X] More padding above and below subsections might help the sidebar visually. (changed color of subheadings to clearly distinguish between sections)

This one is a bit more complex:
> Perhaps moving the sub levels of the sidebar to the top of the relevant page would be easier for the user to navigate?

I'm wary that such a change pushes the content too far down the page. It's great for the shape of laravel content, however when presented with many headings and subheadings e.g., [package.js](http://docs.meteor.com/api/packagejs.html) it gets out of hand. If this is a pressing issue, I'd suggest creating a ticket in the [Meteor hexo theme repo](https://github.com/meteor/hexo-theme-meteor/issues) to discuss it further.

**Comment by dominicnguyen** [comment]
Closing to keep things tidy. Please open new issues for further improvements!
