### ISSUE TITLE
Update references to Promise.denodeify

### ISSUE THREAD

**Issue by olizilla** [meteor/guide#501]
The testing section uses `Promise.denodeify` in it's examples:
https://github.com/meteor/guide/blob/cb44cf3711ad61301ac150930fb9cbbc231855c4/content/testing.md

`Promise.denodeify` is listed as removed in meteor v1.3.3
https://github.com/meteor/meteor/blob/devel/History.md#v133

**Comment by tmeasday** [comment]
@benjamn what should we be using instead of `Promise.denodeify`?

**Comment by rhettlivingston** [comment]
FYI, I just encountered this in bringing the todos app up to Meteor v1.3.4.1. The following is a working denodeify implementation.

```js
  const denodeify = f => (...args) => new Promise((resolve, reject) => {
    f(...args, (err, val) => {
      if (err) {
        reject(err);
      } else {
        resolve(val);
      }
    });
  });
```

I can't find it at the moment, but I remember reading a comment that Ben made when deciding to make the breaking change that included a parallel to the above code for implementing it. 

I'm surprised nobody has come up with a package yet that includes just this. There are some good NPM implementations, and I'm going to try one of them to see if I can get it to work.

I think Ben's words on this breaking change were along the lines of ES6 decided not to include it,,, therefore. But, I did just notice a statement that node 4 and node 6 have it built in. So, @benjamn, might that bring it back in 1.4?

**Comment by tmeasday** [comment]
I think (for now at least) we should update the guide/todos to just include that snippet.

**Comment by rhettlivingston** [comment]
I have two approaches that have "worked" for the todos. Using that snippet "worked". Using an NPM package that does not come with its own promise implementation such as the NPM package "denodeify" also seems to work.

There appears to be a problem with using promises in todos that is independent of this. The instances of denodeify that are there are in test code. When I `meteor npm run test-app-watch` and watch the test in Chrome, everything is great. The test passes reliably. When I `meteor npm run test-app`, one or both of the tests fails and the reasons vary a bit. I believe the problem is that PhantomJS does not have a built-in promise implementation. The promises appear to be returning before the data is ready.

In thinking about this, I've decided I should demonstrate the snippet, not the denodeify package. I have two concerns with the denodeify package. 

1. I'm not 100% positive it will work on server-side (just haven't tried) and
2. the denodeify routines I looked at varied enough to make it obvious that it is unlikely that any of them handles every situation. So perhaps it is better for people to see how they work instead of a black box.

My questions to you, @tmeasday, are a) do those concerns make sense or should I just use the COTS package and b) if I include the denodeify snippet,,, where would it go? There does not seem to be a place in the todos directory structure for a general utility module that is shared between client and server. Perhaps `/imports/utils/denodeify.js`?

**Comment by tmeasday** [comment]
That location seems fine @rhettlivingston.

I took at look at the tests, it does seem to occasionally fail for reasons I can't explain. I did make it a bit more robust though: https://github.com/meteor/todos/commit/f19ef47f65720aeec55adeaca8cec927f7b4b4ae

**Comment by rhettlivingston** [comment]
Thank you! I rebased my changes off of that and the phantomjs now passes where it never passed before.

**Comment by jasonk** [comment]
FYI, I stumbled across this while trying to figure out what denodeify was all about.  I was following the testing guide and while it refers to denodeify, it never actually says where it comes from..

**Comment by tmeasday** [comment]
Yeah, we should probably add a definition (or at least a link to https://github.com/meteor/todos/blob/master/imports/utils/denodeify.js) somewhere in the guide. Care to send a PR?

**Comment by SevenZark** [comment]
One year later and, dealing with the same mystery while reading the Meteor testing guide, I see it still doesn't explain it. I'm glad I found this discussion, at least. :)

**Comment by jSadoski** [comment]
And again several years later, while trying to use https://guide.meteor.com/testing.html#full-app-integration-test.
