### ISSUE TITLE
Logs are gone after meteor build

### ISSUE THREAD

**Issue by manodupont** [meteor/guide#507]
I just used meteor build.

I did npm install.

Then i fixed some packages problems etc. Then i finally come to the point that i can launch the app with
node main.js

But there are no logs ?!?!?! Where are they ?

**Comment by abernix** [comment]
The Meteor bundle that you run with `node main.js` is just a normal `node` application, so none of the usual output that the `meteor` tool itself creates (`Starting`, `Building`, etc.) because it's already built!  Though, in general, unless you add your own `console.log` outputs, etc. there is almost no output under normal usage.

If you need access logs, those are generally provided by a proxy server in front of `node`, such as `nginx` or `haproxy`.

Closing as this is in the Meteor `guide` repo and ultimately, it sounds like things are working properly.
