### ISSUE TITLE
Simplify eslint setup with eslint-config-meteor

### ISSUE THREAD

**Issue by dburles** [meteor/guide#581]
We can greatly simplify configuring eslint by recommending use of the following package: https://github.com/dburles/eslint-config-meteor.

### Reasons why this makes sense:

1. Simplifies configuration. Just add this to your `package.json`:
```
"eslintConfig": {
  "extends": "eslint-config-meteor"
}
```

2. Installation instructions will be documented along with this package. The `npm install ...` command in the guide isn't technically correct.

3. Typically you'll end up having to write a bunch of rules to overwrite airbnb defaults because they make sense for Meteor. e.g. https://github.com/meteor/todos/blob/master/package.json#L42-L63. These can now be handled by eslint-config-meteor and thus be kept in the one place, which should have obvious benefit.

_However_, there is already a package on npm under this name https://www.npmjs.com/package/eslint-config-meteor and I'm not sure whether the author is happy to let us use this name. If not, perhaps it could be published under the `mdg` namespace on npm?

**Comment by yvan-sraka** [comment]
So I just did it: https://github.com/meteor/guide/pull/586 :wink:!

**Comment by lorensr** [comment]
@stubailo I think this would be good as `mdg/eslint-config-meteor` on npm – maybe I could be added to `mdg`, or you could publish and then add `dburles` as a maintainer on the package? 

https://github.com/dburles/eslint-config-meteor
https://www.npmjs.com/~mdg
https://www.npmjs.com/~dburles
https://www.npmjs.com/~lorensr

**Comment by dburles** [comment]
ping @stubailo 🏓

**Comment by stubailo** [comment]
Ahh yes we spent some time communicating with the author of that package and ended up giving up in the end. Perhaps we can just pick some other name such as `eslint-config-meteor-guide` or something?

**Comment by stubailo** [comment]
We could also use the namespace thing but we haven't done that for any other packages in the past. We could start now though.

**Comment by dburles** [comment]
Yeah I had similar success, namespacing may be the way to go as it might help to add an 'official' stamp to it perhaps, given that `eslint-config-meteor` is unavailable.

**Comment by dburles** [comment]
`eslint-config-meteor-guide` is probably not a bad idea either now that I think about it, I'll leave that up to you

**Comment by stubailo** [comment]
I'll leave it to @benjamn or @abernix to decide.

**Comment by hwillson** [comment]
Npm scopes get my vote! There are still some questions to answer (see the discussion on this in the Blaze repo, [starting here](https://github.com/meteor/blaze/issues/11#issuecomment-243290731)), but using an @mdg scope (or better yet [@meteor](https://www.npmjs.com/~meteor) if we could get it) would be the cleanest / most organized approach.

**Comment by benjamn** [comment]
I support namespacing! We've talked about using `@meteorjs` before, but haven't actually used it for anything yet, so perhaps `@mdg` is the way to go for now.

**Comment by stubailo** [comment]
Ooh I like meteorjs way more than mdg since it refers to the framework and not a company.

**Comment by lorensr** [comment]
@tmeasday has https://www.npmjs.com/org/meteorjs/ – maybe he can add ben and sashko as superadmins, and someone can publish this package (I'd also be up to) and add dburles to it?

**Comment by tmeasday** [comment]
@benjamn is an admin already, I don't recall what's @stubailo's npm username is, but Ben can take it from here I guess :)

**Comment by abernix** [comment]
If this is still ready, I'd like to get this done and published under [`@meteorjs`](https://www.npmjs.com/org/meteorjs/), as our first official npm package.  I'm leaning toward `@meteorjs/eslint-config-meteor-guide` and I believe the `@meteorjs`+`meteor` redundancy is right in order to comply with `eslint` naming conventions, but correct me if I'm wrong.  The `-guide` suffix seems super appropriate since it's really just our recommended approach from the Guide, though I'm trying to think what _other_ `eslint-config-meteor` we would have in this ecosystem.  In other words, `-guide` might be forever unnecessary?  At least it further differentiates from the existing `eslint-config-meteor`, which has recently seen [new commits](https://github.com/iDoMeteor/eslint-config-meteor/commit/85da6d30e3cef77c071f7b5fe7ba8a8ba6c197a0) and [publishing activity again](https://www.npmjs.com/package/eslint-config-meteor).

This would certainly close a number of issues in the repo here and be a great resource for the community which matches the guide.  Should we also move it into the Meteor GitHub-org to make it super-official, @dburles?

**Comment by dburles** [comment]
@abernix I'm learning towards `@meteorjs/eslint-config-meteor` for the reasons you mentioned plus it will also cement the fact that it's the official configuration over `eslint-config-meteor`. I'm more than happy to move the repo across.

**Comment by abernix** [comment]
Happy to accept that repo transfer, @dburles.  I think you'll have to transfer it to me and then I can transfer it in the `meteor`-org since [transfers to orgs](https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/#transferring-to-an-organization) only work if the person transferring is admin on the org receiving.  I can then make sure you're still a contributor on it (and others too, for the sake of maintenance).

Alternatively, it is just one file, so I could easily just recreate it. :)

**Comment by dburles** [comment]
@abernix just transferred to you!

**Comment by abernix** [comment]
@dburles Thanks! Transfer received... and transferred again ➡️ https://github.com/meteor/eslint-config-meteor :smile:

The existing `git remote` addresses should work, and the redirect from your existing repo appears to be working as well: https://github.com/dburles/eslint-config-meteor.

I'll see about publishing this real soon!

**Comment by abernix** [comment]
Published as our first `@meteorjs` org-scoped npm package, `@meteorjs/eslint-config-meteor`!

https://www.npmjs.com/package/@meteorjs/eslint-config-meteor

If anyone has time to test this, I'd appreciate it.  I'm a bit busy with a few other things – I'm assuming already that the `README` needs to have the `eslintConfig` changed to use the `@meteorjs` scope too but wasn't sure.  PRs accepted on https://github.com/meteor/eslint-config-meteor :smile:

I guess we need to test then update the Guide.

**Comment by dburles** [comment]
@abernix nice, I've just updated the readme to reflect the correct location

**Comment by abernix** [comment]
@dburles Published!

**Comment by yvan-sraka** [comment]
@abernix Thank you very much!
