### ISSUE TITLE
Excessive processor usage on https://guide.meteor.com/testing.html

### ISSUE THREAD

**Issue by bektar** [meteor/guide#607]
I get 100% processor usage by just having the https://guide.meteor.com/testing.html open. This is reproducible with both Safari Version 10.0.2 (12602.3.12.0.1), Chrome Version 55.0.2883.95 (64-bit) as well as Firefox 51.0.1 (64-bit)

**Comment by lorensr** [comment]
Thanks for reporting! Happening on all the Guide pages I try. CPU too busy for devtools profiling to work most of the time 😆 but I got the sense it might be olark or the commenting plugin

**Comment by lorensr** [comment]
And the docs. There used to be discuss forum comments on the bottom of each page. Maybe that was removed intentionally, or maybe the plugin is desperately trying to display them 😊

**Comment by abernix** [comment]
Should be fixed.  Took some juggling to get the theme updated too due to some unrelated problems. Please test and report back!

This was reproducible locally as well.  The problem went away if I remove the `<script>` tag for `docsearch.js`.  We're were using version `1`, which I believe translates to `1.4.4` (ala `^1.0.0` in semver-land).  The issue didn't go away if I update to `2` (as in, the latest, `2.2.1`), but it did go away if I changed to specifically `2.1.8`.  See https://github.com/meteor/hexo-theme-meteor/commit/7f8f86a9501a450cb476fd5d527467711d6d4d46 for more information.

Thank you for reporting this originally, @bektar!

**Comment by bektar** [comment]
0.7% now… much more reasonable :) 

Thanks for the quick fix! 👍
