### ISSUE TITLE
Idea: Tracker Article?

### ISSUE THREAD

**Issue by tmeasday** [meteor/guide#77]
Tracker is obviously highly relevant for the Blaze article but I think folks that are skipping Blaze to use React or Angular still need some understanding of what Tracker is/does.

**Comment by stubailo** [comment]
I think this would be a really good idea. I think it could be a great place to catalogue the different Tracker patterns, integrating with event listeners/promises, different data structures, etc. It could be a more general "client side data/reactivity" article.

**Comment by stubailo** [comment]
It could also cover migration over hot code reload, using local storage, etc?

**Comment by rgoomar** [comment]
I like this idea. I feel like if there is a guide on how tracker works, there may be companies that could utilize Tracker in their projects without having to port everything over to Meteor at once. It's also probably one of the most important libraries in the Meteor platform in my opinion, so it would be good to have an article solely on it.

**Comment by abhiaiyer91** [comment]
I think many of forgotten how to make their own reactive data sources from scratch. When's the last time you saw creating `Tracker.Dependency()` and running with it? Its more important now than ever, that we educate people to use this lower level api so they can control their reactivity!! Just my 2 cents!!

**Comment by mitar** [comment]
From the discussion [here](https://forums.meteor.com/t/tracker-2-0-the-evolution-of-tracker-solutions-to-its-core-problems) we found few main things guide should tell people about Tracker:
* you should use `fields` to limit your Mongo queries to only fields you are interested in, because otherwise computations might be invalidated for you unnecessary
* use something like [computed fields](https://github.com/peerlibrary/meteor-computed-field) package to limit the reactivity only to changes of data, even if inside you get some unnecessary invalidations
  * related to this is to explain a bit more about different equality of variables, see https://github.com/meteor/guide/issues/79

**Comment by skirunman** [comment]
Also some good info https://medium.com/@faceyspacey/the-evolution-of-tracker-solutions-to-its-core-problems-4b9cb90d479a#.w75uuc455

**Comment by skirunman** [comment]
Instead of an article just on Tracker I think this could be combined into an article on managing local state and reactive data sources, see https://github.com/meteor/guide/issues/234

**Comment by stubailo** [comment]
I agree!

**Comment by stubailo** [comment]
Closing in favor of #234
