### ISSUE TITLE
A call for major update of Meteor Guide

### ISSUE THREAD

**Issue by avalanche1** [meteor/guide#799]
It looks like time has come for Meteor Guide to recieve a major update. In order to get in sync with all the great stuff that's been added to Meteor in recent versions.

Also the JS ecosystem is constantly evolving with new tools coming out and some tools becoming obsolete. This needs a major revision. For example the code section about routing simply will not work any more with ReactRouter v4.

While @stubailo was working on it - 't became an *awesome* piece of work. Now we need a dedicated person working on it once again full-time. Community effort just won't cut it.

**Comment by abernix** [comment]
We simply don't have (and never have or will) the resources to put someone on the guide full-time.  Much like all open-source software, community effort will need to be put forward.  I understand you'd love if we hired someone full-time to work on the guide, but let me be very clear: that will not be happening.

If you're finding a section of the guide that doesn't address something you need help with, research it, ask for help on the forums and open an issue with some suggested changes (including proposed solutions).  A broad declaration like this where you're literally telling us what to do isn't super helpful.

If you absolutely can't find the solution, then please open a specific issue covering a specific request, not just making declarations that the "time has come".  Also, if you think we know the answer to every question, we don't.  Help us (and the community) research it! 🤝 

I'm closing this, since this issue isn't actionable and the Guide is always in flux.

**Comment by hwillson** [comment]
Regarding `react-router` 4 specifically, I've just about finished updating `todos` to use it (see https://github.com/meteor/todos/pull/261). Once that's done I'll submit changes to the Guide to update the associated code samples.

**Comment by hwillson** [comment]
Just to add - the `react-router` 4 Guide changes are now being tracked in https://github.com/meteor/guide/issues/800.
