### ISSUE TITLE
Figure out app testing story.

### ISSUE THREAD

**Issue by tmeasday** [meteor/guide#92]
Right now, the todos app is written in the package-only style, which means we can use package tests to do unit + (to some degree) integration tests. But 
  a) some people don’t like that style
  b) with ES2015 modules that won’t be required any more.
  
So at some point (maybe not v1 of the guide) we need to answer the app testing story. Velocity (and e.g. sanjo:jasmine) has a way of running in “integration mode” (I need to investigate this more). There’s also the possibility of Meteor itself running in “test mode”) (see this PR https://github.com/meteor/meteor/pull/4353).

What is best way forward here? Do we recommend velocity (now that it is no longer maintained)? Do we try and get that PR merged? Or something else?

**Comment by queso** [comment]
'Unmaintained' feels like an unfair categorization by anyone at MDG. A PR from May 9th with the hopes of working with MDG makes the recent announcement by the velocity team feel more like giving up out of frustration.

Would love to see the PR discussed more instead of ending up with another piece of Meteor that will die off (ala Blaze) and leave people like my clients with (testing) code that will quickly become useless to them. You can't' very well expect "The Enterprise" to get excited about a framework/platform with a poor testing story.

**Comment by jperl** [comment]
We wrote all of our tests with velocity (unit & some integration tests w/ jasmine, e2e w/ cucumber) and it has been working but there are many drawbacks: slow startup time, weird random bugs like tests rerunning unexpectedly, unexpected timeout failures.

We consulted w/ xolvio for a few months and they dramatically improved these issues -- but we could not continue to keep them on retainer. Our current strategy is to move as many of our packages to pure node so that we can rely on well maintained packages like vanilla mocha. I am exploring using chimp with nightmarejs for cucumber tests (I will post an example when I put it together).

IMO the best thing possible would be if it was really easy to import meteor packages as vanilla node packages and stick with the plethora of existing vanilla node tools out there.

**Comment by pauldowman** [comment]
Yes there are a plethora of existing vanilla node tools, but I think it's good to have a default. Hopefully this guide can help with that. (And I think slow startup time and bugs with Velocity are implementation issues that I expect would be addressed a lot more successfully with more support from MDG). 

But I think the outside-in, end-to-end story needs to be addressed by this guide, whatever it is.

**Comment by stubailo** [comment]
@queso you said:

> Would love to see the PR discussed more instead of ending up with another piece of Meteor that will die off

If the maintainers of Velocity have said they are not interested in working on it anymore, how will the PR help resolve the situation as it is now?

**Comment by queso** [comment]
@stubailo you said: 

> If the maintainers of Velocity have said they are not interested in working on it anymore, how will the PR help resolve the situation as it is now?

I guess you are right, it might not help anything. But I don't see MDG working on an E2E testing solution (or any at all atm), so my hope is that we can stop having this long standing PR and get the changes in to core to make this easier. Just because Sam and Jonas got tired of maintaining this long running PR to make velocity work, doesn't mean that we can fix up velocity and get people working on it. While I think allowing standard Node testing tools could be good, cucumber.js on it's own is kind of complicated with the whole async testing.

If you never accept that PR, Velocity WILL die. If you accept it, we at least have a chance to right the ship here. Either way, with the ball being back in MDG's court, I think we need a more official answer so people can make plans with this mess.

**Comment by stubailo** [comment]
> cucumber.js on it's own is kind of complicated with the whole async testing.

I personally think this isn't a good reason to spend a lot of time implementing a custom Meteor-specific testing solution. There are a ton of things we can all be spending time on to improve the framework, and a lot of complicated things we could be making less complicated. I believe we need to tackle the most important problems first.

I'm pretty convinced that we _need_ to do something about integration tests, since a Meteor-specific solution is unavoidable there, but I believe that end to end tests are not something that needs to be implemented for each framework individually, especially not until we solve the more serious issues.

I think it is _absolutely crucial_ to have _some_ testing solution for every part of a Meteor app. IMO we should focus on these before trying to unite all of the different kinds of testing under one roof.

**Comment by tmeasday** [comment]
I think the e2e testing situation is pretty reasonable using Chimp (or Gagarin if you prefer). It looks like we'll be writing Chimp up for this version of guide -- @timbotnik has been looking into this a little bit, with some success, and Xolvio has recently released a version that supports Mocha which is nice for consistency.

This ticket is specifically confronting the *app-testing* (i.e. for instance unit testing modules in your app that aren't packages) issue. I mean this in opposition to the package-testing story that we have in the guide right now that's sort of constraining.

**Comment by tmeasday** [comment]
(Here's Sam more or less saying the same thing I said above but better: https://forums.meteor.com/t/velocity-update-xolv-io-are-handing-meteor-testing-back-to-the-mdg/13117/20)
