### ISSUE TITLE
Performance optimizations

### ISSUE THREAD

**Issue by tmeasday** [meteor/guide#95]
Should we have an article or at least a section of an article about perf tips?

Things like:
- Be aware of n^2 problems with your publications
  - What I mean here is if any user can do a write that affects all other users, you have an n^2 problem and you won't be able to horizontally scale
- Try to avoid "expensive" MM queries that run often
- If necessary, it can be useful to use a method instead of a publication b/c of MM queries running too often. (Or a publication that aggregates a set of docs into a single one)
- Leaking observers by forgetting to `.stop()` them in publications
- What kind of queries are expensive on the server (i.e. don't use oplog?)
- How to share observers and how it works
- How to share non-observer work between custom publications
- How to use `{fields}` client side to control reactivity

**Comment by queso** [comment]
I would say yes. Probably worth talking about indexes too. And that packages like publish-composite have an n^2 problem with it.

**Comment by tmeasday** [comment]
Can you elaborate on the n^2 thing with publish-composite a little (just to make sure we are talking about the same thing?)

**Comment by queso** [comment]
Sure, I understand what O(N^2) means. I am talking about the fact that when
you want to grab a Collection document and it's children with publish
composite it will run a query for each 'parent' collection document. For
example if we grab 10 blog posts and 5 comments on each, we end up making 1
query for the blog posts and then 10 queries for the child comments.
Obvoiously, with publish-composite, this issue can grow quickly because you
can have children of children. When it comes to database optimizations, it
is better to genreally load your data into one query and grab all the data
out at once. This will cut down on this like TCP/IP call overhead and
generally we can optimize the larger Mongo queries to use an index to speed
up fetching everything all at once.

Worth noting in here, imo. Something like Reactive Publish package might be
better, right @mitar?

**Comment by mitar** [comment]
No, reactive publish has the same issue. So it is best for 1-to-n relations. For n-to-n you should be using something like [PeerDB](https://github.com/peerlibrary/meteor-peerdb) or simply multiple publish endpoints and merge on the client. I do not think it is reasonable to do n-to-n resolving on the server side (outside of MongoDB) because even if you make a complicated logic to resolve n-to-n queries in a smart way (instead of reruning them every time) you would still have to make many queries between the server and MongoDB.

I wrote more about this in the [discussion section of reactive publish](https://github.com/peerlibrary/meteor-reactive-publish#discussion).

So reactive publish internally does not do anything smarter than publish composite to my knowledge (and vice-versa, publish composite does not do anything smarter). The only difference is the API. We all run the same related query every time anything on the base query changes. This works well if the base query is one document, but not well if there are many.

**Comment by tmeasday** [comment]
Hmm. I'm actually not sure it is necessarily true, given the way oplog observe works, that one large observer (that changes often, probably) is better than many small observers.

For instance, observer re-use (between clients) will generally be higher in the smaller observer case.

Does anyone have any benchmarks one way or another on this kind of thing? @avital @arunoda?

**Comment by arunoda** [comment]
We did something similar. It's hard to tell. Seems like having a lot of
smaller once wins. But then again, that create more observers also take
some issues.

We found that observer create time has some fix overhead too. Like the
network call, buffer creation and so on. So it also increase with number of
observers. But didn't check recently.

**Comment by tmeasday** [comment]
Thanks @arunoda. I suspected it might be one of those annoying "it depends" type answers :)

**Comment by arunoda** [comment]
Yeah. That's it.

**Comment by stubailo** [comment]
In the future we should move stuff like input throttling out of UX and into this, once we start writing it.

**Comment by lorensr** [comment]
A few more topics: 

- subscribing to data before the user gets to the template/route (not a scaling performance thing, but an important perceived performance thing)
- caching subscriptions, so you don't have to resub the next time you need the data (#131)
- not unnecessarily re-rendering sections of the UI (eg header/footer, eg with layoutTemplate in IR)
- pre-rendering templates (eg if it takes longer than your target 100ms to render `/post`, then you render `/post` along with `/` on pageload)
- caching template (saves time removing, and time re-creating in future)
  - caching in the DOM: instead of destroying, hide them
  - caching in VDOM: remove tree from DOM, but keep in memory
- non-reactively render
- how to analyze client-side performance with devtools

More details on these items: https://medium.com/parlay-engineering/fixing-your-meteor-app-s-render-performance-a727e918511c#.g4ma6rblz

**Comment by merlinpatt** [comment]
This would be great to see this come out alongside the release of 1.5, since that's all about improving production performance :-)

**Comment by JohnAllen** [comment]
What denotes an "expensive" mini-mongo query?

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

We are going to make many updates to the guide in the next weeks and it's better to focus on issues with recent activity. If you think this issue is still relevant please open a new one.
