### ISSUE TITLE
Static site TODOs

### ISSUE THREAD

**Issue by yyx990803** [meteor/guide#98]
Preview at: http://guide.meteor.com

- [x] Limit main content width
- [x] Code style highlighting
- [x] Content table styling
- [x] Bottom navigation
- [x] Sidebar sub headers
- [x] Mobile responsive styling
- [x] Search box (just styling for now, we'll need to enable [swiftype](https://swiftype.com/) once we set up the official domain)
- [x] Version selection
- [x] add multi nested header
- [x] hook up the real domain
- [x] style strong tags
- [ ] do-not-use code styling
- [x] setup swiftype search

**Comment by stubailo** [comment]
Limit horizontal width on desktop? I feel like 800-900 px is optimal, you don't want it to expand indefinitely.

**Comment by yyx990803** [comment]
Yep, definitely

**Comment by stubailo** [comment]
Can we have multi-level nav in the sidebar? It would be great for some long articles to have different sections and sub-headings.

**Comment by yyx990803** [comment]
I've added sub headings for h2s. It might be too cluttered to do it for h3s as well though.

**Comment by yyx990803** [comment]
I've added sub headings for all h3s in the article - adding more nesting would make the sidebar really cluttered though.

**Comment by izakfilmalter** [comment]
Any reason behind not using meteor for the meteor guide?

**Comment by stubailo** [comment]
It would be great to have a way to style code snippets that shouldn't be used!

**Comment by dburles** [comment]
All light grey or something

**Comment by stubailo** [comment]
Need style for `<strong>` tags

**Comment by zodern** [comment]
I am getting a 404 when visiting the site.

**Comment by yyx990803** [comment]
@zodern we are in the process of moving it to an official domain, so it will be down for a while

**Comment by stubailo** [comment]
Here's my list of feedback items/questions:

1. The dropdown for version selection shouldn’t have a "v” in it. Also, the current version is "1.2.1” rather than "1.2” - should we be following the minor versions as well? Or does 1.2.1 just count as the current version of 1.2?
2. The line spacing on the table of contents is a bit much - if you have a small screen you can’t see very much at all. Perhaps we shouldn’t go with the full ToC in the sidebar, but I feel like the full ToC should be _somewhere_.
3. What do we do about link backcompat? If people start linking to specific sections and we change the titles, we could end up with many broken links.
4. `<ol>` styling should have numbers and not bullet points.
5. Search doesn’t work
6. `<em>` should be italicized
7. `<strong>` should be bold
8. Class names in code snippets are an unreadable white color: http://guide.meteor.com/collections.html#Using_defaultValue_and_cleaning
9. Each page should have an “edit on GitHub” button
10. Our articles are pretty long - is this bad for SEO since Google won’t know how to link to the right heading?

**Comment by yyx990803** [comment]
@stubailo 

2 - Do you mean a dedicated page for the TOC?
3 - Yeah that's a tricky one. We can generate links based on the numbers, e.g. `#1-1`, but then it's tied to the structure of that page.
5 - Swiftype is not set up yet, but should work soon!
10 - Not sure about the implications on that one - if so does that mean we need to break it down into more pages?

**Comment by stubailo** [comment]
1 - I agree, we should just have the minor versions. 1.2.1 should be a default upgrade for anyone on 1.2 already. :white_check_mark: 
2 - After refactoring some of the section titles, I think things look pretty good. Let's leave it how it is. :white_check_mark: 
3 - Tom and I have decided to hard-code IDs on the headers so that we can edit the names later if we want to. :white_check_mark: 
5 - It looks like the search isn't great for finding specific sections of an article - it only gives one result per article, for example. :x: 
10 - Not sure here... hopefully we can always change things if it turns out to be a problem.

**Comment by yyx990803** [comment]
I checked around Swiftype's docs it looks they can only index pages :/
If we want to search for headers as well we might need something different
